 "use client";
import {useState} from "react"; import Link from "next/link"; import {ArrowLeft,ArrowRight,Bot,Hash,Mic2,Sparkles,Shield,Users,Wand2} from "lucide-react";
import {Blueprint,demoBlueprint} from "@/lib/blueprint";
export default function Builder(){
 const [prompt,setPrompt]=useState(""); const [bp,setBp]=useState<Blueprint|null>(null); const [loading,setLoading]=useState(false); const [error,setError]=useState("");
 async function generate(){setLoading(true);setError("");try{const r=await fetch("/api/ai/generate",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({prompt})});const d=await r.json();if(!r.ok)throw new Error(d.error);setBp(d.blueprint)}catch(e){setError(e instanceof Error?e.message:"Generation failed")}finally{setLoading(false)}}
 if(bp)return <Preview bp={bp}/>;
 return <main className="min-h-screen"><header className="border-b border-white/10"><div className="mx-auto flex max-w-7xl items-center justify-between px-6 py-5"><Link href="/" className="flex items-center gap-2 text-sm text-slate-300"><ArrowLeft size={16}/> DiscordBuilder</Link><Link href="/api/auth/discord" className="text-sm text-indigo-300">Login Discord</Link></div></header><section className="mx-auto max-w-4xl px-6 py-20"><div className="text-center"><div className="mx-auto mb-5 grid h-12 w-12 place-items-center rounded-2xl bg-indigo-500/10 text-indigo-300"><Wand2/></div><h1 className="text-4xl font-bold">Describe your Discord server</h1><p className="mx-auto mt-4 max-w-2xl text-slate-400">Prompt Anda dikirim server-side ke OpenAI. API key tidak pernah dikirim ke browser.</p></div><div className="glass mt-10 rounded-3xl p-4"><textarea value={prompt} onChange={e=>setPrompt(e.target.value)} placeholder="Contoh: Buat server komunitas gaming profesional untuk 1.000 member..." className="min-h-52 w-full resize-none bg-transparent p-4 outline-none placeholder:text-slate-600"/><div className="flex flex-wrap gap-2 border-t border-white/10 pt-4">{["gaming","creator","coding"].map(x=><button key={x} onClick={()=>setPrompt(`Buat server komunitas ${x} profesional dengan onboarding, support, moderation, events, roles, dan voice channels.`)} className="rounded-xl border border-white/10 px-3 py-2 text-xs text-slate-400 hover:bg-white/5">{x}</button>)}</div>{error&&<div className="mt-4 rounded-xl border border-red-400/20 bg-red-400/5 p-3 text-sm text-red-300">{error}</div>}<div className="mt-4 flex justify-end"><button disabled={!prompt.trim()||loading} onClick={generate} className="inline-flex items-center gap-2 rounded-xl bg-indigo-500 px-5 py-3 font-semibold hover:bg-indigo-400 disabled:opacity-50">{loading?"Generating with OpenAI…":"Generate Blueprint"} {!loading&&<ArrowRight size={17}/>}</button></div></div></section></main>
}
function Preview({bp}:{bp:Blueprint}){
 const [guild,setGuild]=useState(""); const [deploying,setDeploying]=useState(false); const [msg,setMsg]=useState("");
 async function deploy(){setDeploying(true);setMsg("");try{const r=await fetch("/api/discord/deploy",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({guildId:guild,blueprint:bp})});const d=await r.json();if(!r.ok)throw new Error(d.error);setMsg(`Berhasil: ${d.guild}. ${d.roles} roles, ${d.categories} categories, ${d.channels.length} channels diproses.`)}catch(e){setMsg(e instanceof Error?e.message:"Deployment failed")}finally{setDeploying(false)}}
 return <main className="min-h-screen"><header className="border-b border-white/10"><div className="mx-auto flex max-w-[1500px] items-center justify-between px-5 py-4"><Link href="/builder" className="flex items-center gap-2 text-sm text-slate-300"><ArrowLeft size={16}/> New Blueprint</Link><div className="flex gap-3"><Link href="/api/auth/discord" className="rounded-xl border border-white/10 px-4 py-2 text-sm">Login Discord</Link></div></div></header><div className="mx-auto max-w-[1500px] p-6 md:p-8"><div className="mb-8 flex flex-col justify-between gap-5 md:flex-row md:items-end"><div><div className="flex items-center gap-3"><div className="grid h-12 w-12 place-items-center rounded-2xl bg-indigo-500/10 text-indigo-300"><Bot/></div><div><h1 className="text-3xl font-bold">{bp.name}</h1><p className="mt-1 text-slate-400">{bp.description}</p></div></div></div><div className="flex gap-2"><input value={guild} onChange={e=>setGuild(e.target.value)} placeholder="Discord Server ID" className="w-48 rounded-xl border border-white/10 bg-white/5 px-3 py-2 text-sm outline-none"/><button onClick={deploy} disabled={!guild||deploying} className="rounded-xl bg-indigo-500 px-4 py-2 text-sm font-semibold disabled:opacity-50">{deploying?"Deploying…":"Deploy to Discord"}</button></div></div>{msg&&<div className="mb-6 rounded-xl border border-white/10 bg-white/5 p-4 text-sm text-slate-300">{msg}</div>}<div className="grid gap-4 md:grid-cols-4">{[["Categories",bp.categories.length],["Channels",bp.channels.length],["Roles",bp.roles.length],["Automations",bp.automations.length]].map(([a,b])=><div className="glass rounded-2xl p-5" key={a as string}><p className="text-sm text-slate-500">{a as string}</p><p className="mt-2 text-2xl font-bold">{b as number}</p></div>)}</div><div className="mt-6 grid gap-4 lg:grid-cols-2">{<div className="glass rounded-3xl p-6"><h2 className="font-semibold">Channels</h2><div className="mt-5 grid gap-2">{bp.channels.map(c=><div className="flex items-center gap-2 rounded-xl bg-white/[.03] p-3 text-sm" key={c.key}><span>{c.type==="voice"?<Mic2 size={14}/>:<Hash size={14}/>}</span>{c.name}<span className="ml-auto text-xs text-slate-600">{c.category}</span></div>)}</div></div>}<div className="glass rounded-3xl p-6"><h2 className="font-semibold">Roles & automation</h2><div className="mt-5 grid gap-2">{bp.roles.map(r=><div className="flex items-center gap-2 rounded-xl bg-white/[.03] p-3 text-sm" key={r.key}><Users size={14} className="text-indigo-300"/>{r.name}<span className="ml-auto text-xs text-slate-600">{r.permissions.join(", ")||"No elevated permissions"}</span></div>)}<div className="mt-4 border-t border-white/10 pt-4">{bp.automations.map(a=><div className="flex items-center gap-2 py-2 text-sm" key={a.type}><Shield size={14} className="text-emerald-300"/>{a.type}<span className="ml-auto text-xs text-emerald-300">{a.enabled?"Enabled":"Disabled"}</span></div>)}</div></div></div></div></div></main>
}